service: idea-app-api

provider:
  name: aws
  runtime: python3.7
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  idea-crud:
    handler:  ideas.handler
    events:
      - http:
          path: ideas
          method: post
          cors: true
      - http:
          path: ideas/{id}
          method: patch
          cors: true
      - http:
          path: ideas/{id}
          method: get
          cors: true
      - http:
          path: ideas/{id}
          method: delete
          cors: true
      - http:
          path: ideas
          method: get
          cors: true

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamo-table.yml)}
  # S3 to host the front end
  - ${file(resources/s3-bucket.yml)}
   # TODO: cloundfront
